review: test: add tests for CtCommentIMmpl class
INRIA/spoon pull request #4053
Opened 2021-07-18 09:32 UTC by Rohitesh-Kumar-Jain

#1818

Hi, I have added some new tests for methods of the JavaOutputProcessor class :

These tests are intended to kill this mutation:

<img width="955" alt="Screenshot 2021-07-18 at 3 02 08 PM" src="https://user-images.githubusercontent.com/62026125/126062368-cbcbb32d-1a44-40ce-8132-193ccfc976d6.png">

Link to #3967

2021-07-21 08:01 UTC, slarse requested changes
Hi @Rohitesh-Kumar-Jain,

The test intents are good, but they can be made significantly shorter and even more clear with some slight tweaks.

2021-07-21 08:01 UTC, slarse commented on src/test/java/spoon/test/comment/CommentTest.java
> +		comment.setContent(commentContent);
Same comment about the names.

Can be shortened like so:

```suggestion
		CtComment comment = factory.createComment("testContent", CtComment.CommentType.BLOCK);
```

2021-07-21 08:01 UTC, slarse commented on src/test/java/spoon/test/comment/CommentTest.java
> +		boolean expectedBoolean = ctComment.equals(comment);
Not the expected value.

2021-07-21 10:41 UTC, Rohitesh-Kumar-Jain commented on src/test/java/spoon/test/comment/CommentTest.java
> +		ctComment.setContent(ctCommentContent);
Both of them can be created from the factory, but I created one with CtCommentImpl(), as to emphasize that we are going to check `CtCommentImpl.equals` 😅

2021-07-21 11:03 UTC, Rohitesh-Kumar-Jain commented on src/test/java/spoon/test/comment/CommentTest.java
> +		boolean expectedBoolean = ctComment.equals(comment);
yes will change that as well

2021-07-21 11:34 UTC, Rohitesh-Kumar-Jain commented
Other methods in this class don't need improvement in tests so, there's no hurry to merge this one

2021-07-26 08:49 UTC, slarse approved these changes
LGTM, thanks @Rohitesh-Kumar-Jain

2021-07-26 08:50 UTC, merged