review: fix: get correct descriptions from CtJavaDocImpl
INRIA/spoon pull request #4061
Opened 2021-07-23 15:35 UTC by andrewbwogi

closes #4059

2021-08-09 07:39 UTC, slarse requested changes
@andrewbwogi thanks for the PR, could you have a look at my comment?

2021-08-10 10:13 UTC, monperrus commented
ping @andrewbwogi to complete this one?

2021-08-10 18:05 UTC, slarse commented
Thanks @andrewbwogi, that's nice and easy to read!

2021-08-10 18:05 UTC, slarse approved these changes

2021-08-10 18:05 UTC, merged