fix: NPE in Launcher.prettyprint() (#4302)
INRIA/spoon pull request #4303
Opened 2021-11-20 16:17 UTC by xzel23

This fixes bug #4302

2021-11-21 09:37 UTC, SirYwell commented
You should probably use JUnit 5 (the `@Test` annotation needs to be fully qualified like `@org.junit.jupiter.api.Test` then) and `assertDoesNotThrow(launcher::prettyprint);` instead of the try catch with the `assertTrue`.

There is also a `DefaultJavaPrettyPrinterTest` class (note the `Java`) which already uses JUnit 5, but I'm not sure if it belongs there...

2021-11-23 09:59 UTC, xzel23 commented
Ok, will Look into this later.

2021-11-23 22:10 UTC, slarse commented
For a test class that uses JUnit4, it's fine to add more JUnit4 tests. That actually makes migrating easier than if we mix.

As the test is for the `Launcher` class (it really has nothing to do with the actual printing anyway), the test should go into `LauncherTest`.

Note that I've made no review here, I just looked at the files changed

@MartinWitt can you review this PR?

2021-11-23 22:25 UTC, MartinWitt requested changes

2021-11-23 22:25 UTC, MartinWitt commented on src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
> +			launcher.prettyprint();
here you should use `assertDoesNotThrow(() -> Launcher.prettyPrint())`

2021-11-26 14:24 UTC, xzel23 commented
I have changed the test to use assertDoesNotThrow(). In a second commit, I have moved the test from DefaultPrettyPrinterTest to LauncherTest as suggested by slarse. I noticed that the test failed due to Spoon trying to write to an unwritable directory when I simply move the test method, so I have set the source output directory to a temp dir.

2021-11-26 14:41 UTC, MartinWitt commented on src/test/java/spoon/LauncherTest.java
> +		launcher.setSourceOutputDirectory(tmpDir);
https://spoon.gforge.inria.fr/mvnsites/spoon-core/apidocs/spoon/compiler/Environment.html#setOutputType(spoon.OutputType) Here you can simply set the `OutputType` to none, which is better than creating temp files.

2021-11-26 14:41 UTC, MartinWitt commented on src/test/java/spoon/test/prettyprinter/DefaultPrettyPrinterTest.java
> +import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
Can you restore the file to the original state, for a minimal diff?

2021-11-26 14:51 UTC, MartinWitt commented
LGTM will merge after 24 hours.

2021-11-27 09:35 UTC, slarse commented
@MartinWitt You don't need to wait 24 hours after the final change, but from the point that the PR was opened. This is more to let other integrators have their say about the intent of the PR rather than the final content. After that we trust the judgement of individual integrators.

Of course, if there are multiple reviewers on a PR, then it may be good to wait for the other(s) to cast their votes. But otherwise, you're free to merge at your discretion after the PR has been open for 24 hours.

2021-11-27 15:09 UTC, merged

2021-11-27 15:14 UTC, MartinWitt commented
Thanks @xzel23