wip: refactor(*): Convert test package to junit5
INRIA/spoon pull request #4387
Opened 2021-12-27 20:45 UTC by MartinWitt

The following has changed in the code:
In type spoon.test.strings.StringLiteralTest:
- Replaced junit 4 test annotation with junit 5 test annotation in testSnippetFullClass
In type spoon.test.strings.StringTest:
- Replaced junit 4 test annotation with junit 5 test annotation in testModelBuildingInitializer

2021-12-28 10:58 UTC, SirYwell commented
I think the assertions should be updated to JUnit 5 too

2021-12-28 11:17 UTC, slarse commented
> I think the assertions should be updated to JUnit 5 too

Indeed, see #3919

2021-12-30 15:24 UTC, slarse requested changes
Also replace assertions with JUnit5 equivalents

2022-01-02 09:36 UTC, slarse approved these changes

2022-01-02 09:37 UTC, merged