Issue4377: spoon adds invalid assignments in record compact constructor (in progress)
INRIA/spoon pull request #4389
Opened 2021-12-29 12:59 UTC by xzel23

I have created a second test case for record compact constructors to demostrate the problem. I have created a PR even if I don't have a fix yet to make reproducing easier: either run CtRecordTest.testCompactConstructor2() directly from your IDE (in IntelliJ it's possible to run disabled tests from the IDE, don't know about eclipse), or remove the "@Disabled" annotation from said method.

2021-12-29 16:48 UTC, xzel23 commented
Please review. This fixes #4377.

2021-12-30 15:19 UTC, slarse commented
@SirYwell can you review this?

@xzel23 Could you please add "fix #4377" to the PR body (first post)? That will automatically close the issue when this is merged. See this line of the [contributing guidelines](https://github.com/INRIA/spoon/blob/master/CONTRIBUTING.md)

> If the pull request resolves an issue, simply add "fix #issueNumber" or "close #issueNumber" to the description, see [doc](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

2021-12-30 17:20 UTC, SirYwell requested changes
I left two comments for possible improvements. The fix itself looks good.

I also figured out why I wasn't able to reproduce it, as I even checked out your commit before you added the fix. I ran the tests with Java 11 locally, and as JDT can't resolve `java.lang.Record` there, it does not add the assignments... :)

2022-01-04 18:13 UTC, xzel23 commented on src/test/java/spoon/test/record/CtRecordTest.java
> +import org.junit.jupiter.api.Disabled;
removed the imports, will update the PR once I'm done with the other comments and unit tests are green

2022-01-04 18:20 UTC, xzel23 commented on src/main/java/spoon/support/compiler/jdt/ContextBuilder.java
> +		}
Yes, that's of course much better.

2022-01-05 07:43 UTC, SirYwell approved these changes
Looks good!

2022-01-06 08:33 UTC, merged

2022-01-06 08:33 UTC, monperrus commented
Thanks a lot @xzel23 for the fix and @SirYwell for the review.