test: migrate CloneTest to Junit 5
INRIA/spoon pull request #4401
Opened 2022-01-05 22:09 UTC by MartinWitt

#3919 As always as clean as the sniper printer can produce.
The following has changed in the code:
Replaced junit 4 test annotation with junit 5 test annotation in testCloneMethodsDeclaredInAST
Replaced junit 4 test annotation with junit 5 test annotation in testCloneCastConditional
Replaced junit 4 test annotation with junit 5 test annotation in testCloneListener
Replaced junit 4 test annotation with junit 5 test annotation in testCopyMethod
Replaced junit 4 test annotation with junit 5 test annotation in testCopyType
Replaced junit 4 test annotation with junit 5 test annotation in testIssue3389
Replaced junit 4 test annotation with junit 5 test annotation in testCloneKeepsImplicitModifierState
Replaced junit 4 test annotation with junit 5 test annotation in testCloneClonesExtendedModifiers
Transformed junit4 assert to junit 5 assertion in testCloneListener
Transformed junit4 assert to junit 5 assertion in testCopyMethod
Transformed junit4 assert to junit 5 assertion in testCopyType
Transformed junit4 assert to junit 5 assertion in testIssue3389
Transformed junit4 assert to junit 5 assertion in testCloneKeepsImplicitModifierState
Transformed junit4 assert to junit 5 assertion in assertModifierImplicitness
Transformed junit4 assert to junit 5 assertion in assertModifiersAreDistinctInstances

2022-01-06 08:29 UTC, monperrus commented
thanks @MartinWitt. 

there are too many formatting changes to check for the absence of semantic differences.

@MartinWitt could you sniper print instead?

or

@algomaster99 could you generate an AST diff?

2022-01-06 08:53 UTC, slarse requested changes
Looks semantically fine, but there's some really odd formatting that I'd like fixed.

@monperrus This is either manually edited or sniper printed. The "formatting changes" are due to the message parameter switching place in all assertions going from JUnit4 to JUnit5.

2022-01-06 08:53 UTC, slarse commented on src/test/java/spoon/reflect/ast/CloneTest.java
> +		assertEquals(2, clonedTest.getExtendedModifiers().size(), "Clone has wrong amount of modifiers"
Could you manually pull up the `);` from the next line to this one? Looks very odd right now.

2022-01-06 08:53 UTC, slarse commented on src/test/java/spoon/reflect/ast/CloneTest.java
> +				assertEquals(shouldBeImplicit, modifier.isImplicit(), "Unexpected CtExtendedModifier#isImplicit"
Same

2022-01-06 08:53 UTC, slarse commented on src/test/java/spoon/reflect/ast/CloneTest.java
> +		assertEquals(4, referenceBasedModifierSet.size(), "The extended modifiers are the same instance as the original"
Same

2022-01-06 09:16 UTC, MartinWitt commented
I am sniper printing, but junit 5 swapped the String message from first to last place.

2022-01-06 09:36 UTC, algomaster99 commented
> could you generate an AST diff?

I will see if I can host the ASTDiff in [diffmin-examples](https://github.com/algomaster99/diffmin-examples) repository. Currently, that's the best method to view the diff if someone doesn't have a local setup on their machine.

2022-01-06 10:19 UTC, algomaster99 commented
@monperrus have a look at the diff [here](https://algomaster99.github.io/diffmin-examples/spoon%234401%23504196f.html).

2022-01-06 11:01 UTC, MartinWitt commented
@algomaster99 have you thought about creating a github app posting these diffs under PRs?

2022-01-06 11:28 UTC, algomaster99 commented
@MartinWitt yes, I am currently collecting examples where AST diff might be easier to review than line diff. I collect samples here - https://github.com/algomaster99/diffmin-examples.

@monperrus and I will work on how we could make reviewing pull requests easier. This repository will provide motivational examples for it.

2022-01-07 08:40 UTC, slarse approved these changes
Thanks @MartinWitt

2022-01-07 08:40 UTC, merged