doc: Update Documentation FAQ to add question about pretty printing
INRIA/spoon pull request #4641
Opened 2022-03-16 05:21 UTC by LakshyAAAgrawal

2022-03-16 08:23 UTC, monperrus commented
Thanks a lot @LakshyAAAgrawal , Improved it. Will merge.

2022-03-16 08:53 UTC, algomaster99 requested changes
Thanks for your PR. I think it is worthwhile to mention the default output directory as well.

2022-03-16 08:53 UTC, algomaster99 commented on doc/faq.md
> +```launcher.prettyprint``` prints the model on disk. The model could have been transformed or not, and is saved in an output directory which one can set up with ```launcher.setSourceOutputDirectory()
```suggestion
```launcher.prettyprint``` prints the model on disk. The model could have been transformed or not, and is saved in an output directory which one can set up with ```launcher.setSourceOutputDirectory()```. The default output directory is called `spooned`. If you want the pretty-print to the standard output (console STDOUT), use method `toString` instead, defined for every CtElement. Reference: https://github.com/INRIA/spoon/issues/4274
```

2022-03-21 06:25 UTC, merged

2022-03-21 06:25 UTC, monperrus commented
Thanks a lot @LakshyAAAgrawal  for the doc PR! Thanks @algomaster99 for your attention to details.