review: fix: getTypeDeclaration() on nested record type
INRIA/spoon pull request #5015
Opened 2022-11-17 19:53 UTC by I-Al-Istannen

The nested visitor did not consider records as it was written before their existence.

We might want to find a better upgrade story for such cases.

2022-12-20 12:09 UTC, MartinWitt approved these changes

2022-12-20 12:09 UTC, MartinWitt commented
@I-Al-Istannen @SirYwell could both of you also mark this PR for approval (after a review) and we simply merge it?

2022-12-20 12:17 UTC, I-Al-Istannen commented
Github won't let me approve it as I am the author. But consider this my approval :P

2022-12-21 14:26 UTC, SirYwell submitted a review, later dismissed

2022-12-22 12:41 UTC, MartinWitt commented
@monperrus could you have a brief look and merge this PR? As all of us three are (co)authors.

2022-12-25 11:00 UTC, slarse requested changes
Looks functionally correct, I have a couple of minor comments

2022-12-25 16:48 UTC, I-Al-Istannen commented on src/test/java/spoon/test/ctType/CtTypeTest.java
> +		}
Yea, very good point. I have broken a few testsuites in the past without noticing any failure… `∀` for an empty set isn't as meaningful as you would hope :P

I opted for an adaption of `b)` which should behave identically. I hope that's okay.

2022-12-25 16:49 UTC, I-Al-Istannen commented on src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
> +					throw new SpoonException("Unknown type, extend scanner: " + e.getClass());
Good point, I have changed the wording. Is it fine with you or do you want further changes to it :)

2022-12-26 16:11 UTC, slarse approved these changes
LGTM, thanks everyone. Now to see if I can manage to merge without removing all coauthorships.

2022-12-26 16:11 UTC, slarse commented on src/main/java/spoon/support/reflect/declaration/CtTypeImpl.java
> +					throw new SpoonException("Unknown type, extend scanner: " + e.getClass());
Looks good!

2022-12-26 16:11 UTC, slarse commented on src/test/java/spoon/test/ctType/CtTypeTest.java
> +		}
:+1:

2022-12-26 16:12 UTC, merged

2022-12-31 12:08 UTC, monperrus commented
thanks all!