fix: Remove escaping of ' in a CtLiteral<String>
INRIA/spoon pull request #5070
Opened 2023-01-10 16:14 UTC by MartinWitt

Currently, spoon escapes every `'` in a `CtLiteral<String>` without a source position. In a `string `escaping `'` is not necessary.

2023-01-10 16:27 UTC, MartinWitt commented
I could create another method overload* to fix the constant value warning. But this would increase the size of the class unnecessary. Any opinions? 

* Actually this is not a method overload because the methods are static

2023-01-13 11:37 UTC, I-Al-Istannen commented
> `	 * This exists for backwards compatibility`

The method seems  to be package private, why do you need to keep it if it is never called?

2023-01-13 15:12 UTC, MartinWitt commented
I thought about the one guy creating his code inside the same package in his project. I can remove this method if we ignore that one guy.

2023-01-13 15:13 UTC, I-Al-Istannen commented
Yes, I would ignore them.

2023-03-05 15:43 UTC, MartinWitt commented on src/main/java/spoon/reflect/visitor/LiteralHelper.java
> +				appendCharLiteral(sb, value.charAt(i), true, true);
This fixes the qodana warning, I have no clue if this is a better code style.

2023-03-05 19:12 UTC, I-Al-Istannen requested changes

2023-04-06 08:23 UTC, I-Al-Istannen approved these changes

2023-04-06 08:24 UTC, merged