Leading-constrictor
INRIA/spoon pull request #5294
Opened 2023-06-19 19:49 UTC by MartinWitt

2023-06-19 20:11 UTC, MartinWitt commented
Given the current design, the new method has to return null. Any empty `CtTypeReference` is not helpful and hides the error.

2023-06-20 13:58 UTC, I-Al-Istannen requested changes

2023-06-20 13:58 UTC, I-Al-Istannen commented on src/test/resources/jdk/Class.java
I'd be for minimizing this and recreating the bug :^)

2023-06-23 16:52 UTC, MartinWitt commented
I haven't found any small reproducer, so lets close this and live with the bug.

2023-06-30 13:46 UTC, I-Al-Istannen commented
I'd be in favor of deleting the test and merging it without any. The change is localized to an if that is not triggered by anything currently (or crashes), so we can't really make stuff worse.

2023-06-30 14:05 UTC, I-Al-Istannen approved these changes

2023-07-03 09:22 UTC, merged