doc: Add Javadoc Analysis to sidebar and deprecate old Javadoc classes
INRIA/spoon pull request #5609
Opened 2024-01-10 15:50 UTC by MartinWitt

Added Javadoc Analysis section in the sidebar_doc.yml file. Deprecated several old classes related to the handling of Javadoc comments in favor of the new javadoc parser submodule. Updated the installation instructions in spoon_javadoc.md to reflect these changes.

resolves #5606

2024-01-10 19:04 UTC, I-Al-Istannen requested changes

2024-01-10 19:04 UTC, I-Al-Istannen commented on doc/spoon_javadoc.md
> +    <version>$CurrentVersion</version>
```suggestion
    <version>$currentVersion</version>
```

2024-01-10 19:04 UTC, I-Al-Istannen commented on src/main/java/spoon/javadoc/internal/JavadocBlockTag.java
> +* @deprecated Use the new javadoc parser submodule, See <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```suggestion
* @deprecated Use the new javadoc parser submodule, see <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```

2024-01-10 19:04 UTC, I-Al-Istannen commented on src/main/java/spoon/javadoc/internal/JavadocDescription.java
> +	* @deprecated Use the new javadoc parser submodule, See <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```suggestion
	* @deprecated Use the new javadoc parser submodule, see <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```

2024-01-10 19:04 UTC, I-Al-Istannen commented on src/main/java/spoon/javadoc/internal/JavadocDescriptionElement.java
> +* @deprecated Use the new javadoc parser submodule, See <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```suggestion
* @deprecated Use the new javadoc parser submodule, see <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```

2024-01-10 19:04 UTC, I-Al-Istannen commented on src/main/java/spoon/javadoc/internal/JavadocInlineTag.java
> +* @deprecated Use the new javadoc parser submodule, See <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```suggestion
* @deprecated Use the new javadoc parser submodule, see <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```

2024-01-10 19:04 UTC, I-Al-Istannen commented on src/main/java/spoon/javadoc/internal/JavadocSnippet.java
> +* @deprecated Use the new javadoc parser submodule, See <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```suggestion
* @deprecated Use the new javadoc parser submodule, see <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```

2024-01-10 19:22 UTC, I-Al-Istannen approved these changes

2024-01-18 12:03 UTC, I-Al-Istannen commented
Can you split this in two PRs please, one for the doc changes and one for the deprecation?

2024-01-22 19:01 UTC, MartinWitt commented
Good point. I will also switch the target for the website fix/doc to current master and the deprecation to java 17.

2024-01-24 18:43 UTC, I-Al-Istannen requested changes

2024-01-24 18:43 UTC, I-Al-Istannen commented on src/main/java/spoon/javadoc/internal/Javadoc.java
> + * @deprecated Use the new javadoc parser submodule, See <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```suggestion
 * @deprecated Use the new javadoc parser submodule, see <a href="https://spoon.gforge.inria.fr/spoon_javadoc.html">Javadoc Parser</a>.
```

2024-01-28 11:47 UTC, merged