wip: refactor: rework CtGenerationTest to minimize unrelated diff
INRIA/spoon pull request #5744
Opened 2024-04-07 07:17 UTC by SirYwell

During the work on Java 21 features and #5674 we noticed that `CtGenerationTest` always generates diffs for the license headers and file endings.

This PR aims to clean up the code to allow generating the exactly same content, especially
- license headers with `*` prefixes
- newlines at the end of the file
- including all template classes in the license formatter
- update the outdated licenses

I'm not sure if it makes sense to change the printer behavior this way, I'm open for better ideas.

2024-04-07 07:17 UTC, SirYwell commented on src/main/java/spoon/reflect/meta/impl/ModelRoleHandlers.java
> +
I have no clue why this changed now, feel free to debug :)

2024-04-17 18:47 UTC, MartinWitt commented on src/main/java/spoon/reflect/visitor/CommentHelper.java
> +					};
maybe this is the once in a lifetime place for `s.isEmpty ? " *" : " * " + s` ?

2024-04-20 10:25 UTC, I-Al-Istannen requested changes

2024-04-20 10:25 UTC, I-Al-Istannen commented on src/test/java/spoon/processing/CtGenerationTest.java
> +
Can you use tabs here instead of spaces to be consistent and fix the indentation of the comment?

2024-06-02 11:01 UTC, I-Al-Istannen approved these changes

2024-06-05 10:23 UTC, merged